Update interest calculation for collateral custodies
solana-labs/perpetuals pull request #25
Opened 2023-07-25 15:12 UTC by askibin

2023-07-27 11:20 UTC, mzs-dev commented
Don't think this fixes the issue with misappropriated computation of interest.
The proposed change here: https://github.com/askibin/perpetuals-fork/blob/86c3f3498019807a89df9f54ab85be76008812dc/programs/perpetuals/src/state/custody.rs#L497-L498 does account for proper tracking of interest accrued on collateral custody in case of shorts or virtual asset positions.
However we're computing the wrong interest amount in case of shorts here: https://github.com/askibin/perpetuals-fork/blob/86c3f3498019807a89df9f54ab85be76008812dc/programs/perpetuals/src/state/custody.rs#L444
and updating the stats here: https://github.com/askibin/perpetuals-fork/blob/86c3f3498019807a89df9f54ab85be76008812dc/programs/perpetuals/src/state/custody.rs#L453
Which is included in pool aum calculations here: https://github.com/solana-labs/perpetuals/blob/2b715801f5531c7d75800acfe1e9f25c18d20700/programs/perpetuals/src/state/pool.rs#L756-L799

2023-07-27 11:22 UTC, mzs-dev requested changes

2023-07-27 11:22 UTC, mzs-dev commented on programs/perpetuals/src/state/custody.rs
> +            let collective_position = custody.get_collective_position(position.side)?;
need to add additional changes to pool aum calculations to fix the issue

2023-07-27 14:18 UTC, askibin commented
agree, the interest was counted twice for shorts/virtual, in both custody and collateral_custody, updated

2023-07-29 09:16 UTC, mzs-dev approved these changes
Looks good now...
I'd still want to have a seperate market state to track

2023-07-31 20:49 UTC, askibin commented on programs/perpetuals/src/instructions/open_position.rs
> +    position.borrow_size_usd = size_usd;
updated

2023-08-03 17:29 UTC, merged